/*==============================================================*/
/* Nom de SGBD :  ORACLE Version 10gR2                          */
/* Date de cr�ation :  07/09/2020 11:08:52                      */
/*==============================================================*/

INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Lassalle','Justin',10,'Slovénie');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Lorreyte','Jules',450,'Mongolie');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Sparrow', 'Jack',1, 'Bahamas');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Azalbert','Victor',17,'Turquie');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Guinaldo','Vincent',200,'France');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Federer','Roger',2,'Suisse');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Nadal','Rafael',3,'Espagne');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Debouzze','Jammel',1000,'France');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Paire','Benoit',4,'France');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Noah','Yannick',5,'France');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Douet','Quentin',400,'France');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Jackson','Michael',2200,'USA');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Roddick','Andy',7,'USA');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Gasquet','Richard',6,'France');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Llodra','Mickael',14,'France');
INSERT INTO JOUEUR (JONAME,JOSURNAME,JOCLASS,JOCOUNTRY) VALUES ('Esterle','Jean',20,'France');

INSERT INTO ARBITRE(ARNAME,ARSURNAME,ARCUNTRY) VALUES ('Bernardes','Carlos','Brésil');
INSERT INTO ARBITRE(ARNAME,ARSURNAME,ARCUNTRY) VALUES ('Kaeothavongue','James','Angleterre');

INSERT INTO UTILISATEUR(UNAME,USURNAME,UMDP) VALUES ('Flantier','Noel','Oss117');
INSERT INTO UTILISATEUR(UNAME,USURNAME,UMDP) VALUES ('Wayne','Bruce','Batman');

INSERT INTO TOURNOI (USERID,TONAME,TOPLACE,TOSTARTDATE,TOENDDATE,TONUMBER,TORULES) VALUES (1,'Tournoi Exhibition','Saubusse',TO_DATE('2020/09/07', 'yyyy/mm/dd'),TO_DATE('2020/09/21', 'yyyy/mm/dd'),16,'3 sets gagnants');

INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',1,2,1,TO_DATE('2020/09/07', 'yyyy/mm/dd'),'6/2 6/3 4/6 6/1','Joueur 1');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',3,4,2,TO_DATE('2020/09/07', 'yyyy/mm/dd'),'6/2 6/3 6/7 6/4','Joueur 2');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',5,6,1,TO_DATE('2020/09/07', 'yyyy/mm/dd'),'3/6 7/6 6/3 4/6 6/1','Joueur 2');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',7,8,2,TO_DATE('2020/09/07', 'yyyy/mm/dd'),'6/2 6/3 6/1','Joueur 1');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',9,10,1,TO_DATE('2020/09/08', 'yyyy/mm/dd'),'6/0 6/0 6/0','Joueur 1');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',11,12,2,TO_DATE('2020/09/08', 'yyyy/mm/dd'),'0/6 7/6 0/6 7/6 8/6','Joueur 2');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',13,14,1,TO_DATE('2020/09/08', 'yyyy/mm/dd'),'6/4 4/6 6/3 2/6 6/4','Joueur 2');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Huitièmes',15,16,2,TO_DATE('2020/09/08', 'yyyy/mm/dd'),'6/0 6/0 6/0','Joueur 1');

INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Quarts',1,4,1,TO_DATE('2020/09/10', 'yyyy/mm/dd'),'6/0 6/0 6/0','Joueur 1');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Quarts',6,7,2,TO_DATE('2020/09/11', 'yyyy/mm/dd'),'3/6 7/6 6/3 4/6 6/1','Joueur 2');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Quarts',9,12,1,TO_DATE('2020/09/12', 'yyyy/mm/dd'),'6/1 0/6 6/0 0/6 14/12','Joueur 1');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Quarts',14,15,2,TO_DATE('2020/09/13', 'yyyy/mm/dd'),'6/4 6/4 6/4','Joueur 1');

INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Demis',1,7,1,TO_DATE('2020/09/17', 'yyyy/mm/dd'),'6/1 6/2 6/4','Joueur 1');
INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Demis',9,14,2,TO_DATE('2020/09/19', 'yyyy/mm/dd'),'6/0 6/0 6/4','Joueur 2');

INSERT INTO MATCH (TOID,MATOUR,JOID,JOU_JOID,ARID,MADATE,MASCORE,MAWINNER) VALUES (1,'Finale',1,14,1,TO_DATE('2020/09/21', 'yyyy/mm/dd'),'6/1 2/6 6/2 4/6 82/80','Joueur 1');
