/*Trigger pour ajouter l'auto-increment sur l'ID*/
CREATE SEQUENCE SEQ_ARBITRE START WITH 1;

CREATE OR REPLACE TRIGGER ARBITRE_ON_INSERT
   BEFORE INSERT ON ARBITRE
   FOR EACH ROW
BEGIN
  SELECT SEQ_ARBITRE.NEXTVAL
  INTO   :new.arid
  FROM   dual;
END;
/


/*Trigger pour ajouter l'auto-increment sur l'ID*/
CREATE SEQUENCE SEQ_JOUEUR START WITH 1;

CREATE OR REPLACE TRIGGER JOUEUR_ON_INSERT
   BEFORE INSERT ON JOUEUR
   FOR EACH ROW
BEGIN
  SELECT SEQ_JOUEUR.NEXTVAL
  INTO   :new.joid
  FROM   dual;
END;
/


/*Trigger pour ajouter l'auto-increment sur l'ID*/
CREATE SEQUENCE SEQ_MATCH START WITH 1;

CREATE OR REPLACE TRIGGER MATCH_ON_INSERT
   BEFORE INSERT ON MATCH
   FOR EACH ROW
BEGIN
  SELECT SEQ_MATCH.NEXTVAL
  INTO   :new.maid
  FROM   dual;
END;
/


/*Trigger pour ajouter l'auto-increment sur l'ID*/
CREATE SEQUENCE SEQ_TOURNOI START WITH 1;

CREATE OR REPLACE TRIGGER TOURNOI_ON_INSERT
   BEFORE INSERT ON TOURNOI
   FOR EACH ROW
BEGIN
  SELECT SEQ_TOURNOI.NEXTVAL
  INTO   :new.toid
  FROM   dual;
END;
/



/*Trigger pour ajouter l'auto-increment sur l'ID*/
CREATE SEQUENCE SEQ_UTILISATEUR START WITH 1;

CREATE OR REPLACE TRIGGER UTILISATEUR_ON_INSERT
   BEFORE INSERT ON UTILISATEUR
   FOR EACH ROW
BEGIN
  SELECT SEQ_UTILISATEUR.NEXTVAL
  INTO   :new.userid
  FROM   dual;
END;
/
